### ISSUE TITLE
Question about translation

### ISSUE THREAD

**Issue by hopper08** [wet-boew/theme-gc-intranet#127]
Hi, 
I just have a quick question. I have a multilingual (English/French) site that uses the Tabbed Interface component, but the translation for the Play/Pause button doesn't seem to be working in IE (it works fine in Firefox and Chrome). Pause in French is still Pause, so that's alright, but the Play button still stays Play instead of Jouer in French.

I'm trying to figure out what in my site might be conflicting and stopping the translation from happening. 
Any suggestions/ideas on where to look and how to debug this?

**Comment by pjackson28** [comment]
The language of the button is dependent upon the <code>lang</code> attribute on the <code>html</code> element. Make sure that on French pages that you have <code>lang="fr"</code> on the <code>html</code> element.

**Comment by hopper08** [comment]
the html tag has xml:lang="fr" on it.
Why would the translation work fine in FF and Chrome, but not IE?

**Comment by pjackson28** [comment]
It needs to be <code>lang="fr"</code> instead of <code>xml:lang="fr"</code>. Perhaps FF and Chrome interpret <code>xml:lang</code> as <code>lang</code> when the <code>lang</code> attribute is absent while IE doesn't. Note that there is no requirement for IE to do that since "The attribute in no namespace with no prefix and with the literal localname "xml:lang" has no effect on language processing." (taken from the HTML Standard).

**Comment by hopper08** [comment]
It works, that you so much for the advice!
